import { lazy } from 'react';

// Vite trick: Load all components synchronously ONLY during Server-Side Rendering (SSG build)
// This prevents <Suspense> fallbacks in the generated static HTML.
// For the browser, it remains fully lazy loaded for optimal Core Web Vitals.
const blogModules = import.meta.glob('./*.tsx');
const eagerModules = import.meta.env.SSR 
  ? import.meta.glob('./*.tsx', { eager: true, import: 'default' }) 
  : {} as Record<string, any>;

const getBlogComponent = (filename: string) => {
  const path = `./${filename}.tsx`;
  if (import.meta.env.SSR) {
    return eagerModules[path] || (() => null);
  }
  const importFn = blogModules[path];
  if (!importFn) return (() => null) as any;
  return lazy(importFn as any);
};

export const BlogRegistry: Record<string, any> = {
  'automate-data-erasure': getBlogComponent('AutomatedErasureBlog'),
  'best-data-erasure-methods': getBlogComponent('BestErasureMethodBlog'),
  'caption-call-fcc-settlement': getBlogComponent('CaptionCallFCCSettlementBlog'),
  'caption-call-settlement': getBlogComponent('CaptionCallSettlementBlog'),
  'carbon-footprint-erasure': getBlogComponent('CarbonFootprintErasureBlog'),
  'ccpa-violation': getBlogComponent('CCPAViolationBlog'),
  'certified-itad-reasons': getBlogComponent('ComplianceVerifiedITADReasonsBlog'),
  'change-healthcare-attack': getBlogComponent('ChangeHealthcareAttackBlog'),
  'chromebook-data-risks': getBlogComponent('ChromebookDataRisksBlog'),
  'cloud-migration': getBlogComponent('CloudMigrationBlog'),
  'common-criteria': getBlogComponent('CommonCriteriaBlog'),
  'common-criteria-certified-data-wiping': getBlogComponent('CommonCriteriaComplianceVerifiedDataWipingBlog'),
  'corporate-it-asset-risks': getBlogComponent('CorporateITAssetRisksBlog'),
  'cryptographic-erase': getBlogComponent('CryptographicEraseBlog'),
  'cryptographic-erase-nist': getBlogComponent('CryptographicEraseNISTBlog'),
  'cybersecurity-data-destruction': getBlogComponent('CybersecurityDataDestructionBlog'),
  'dark-data-risks': getBlogComponent('DarkDataRisksBlog'),
  'data-deletion-myths': getBlogComponent('DataDeletionMythsBlog'),
  'data-destruction-best-practices': getBlogComponent('DataDestructionBestPracticesBlog'),
  'data-disposal-guidelines': getBlogComponent('DataDisposalGuidelinesBlog'),
  'data-erasure-disaster-recovery': getBlogComponent('DataErasureDisasterRecoveryBlog'),
  'data-erasure-for-non-profits': getBlogComponent('DataErasureForNonProfits'),
  'data-erasure-myths': getBlogComponent('DataErasureMythsBlog'),
  'data-hoarding': getBlogComponent('DataHoardingBlog'),
  'data-hoarding-risks': getBlogComponent('DataHoardingRisksBlog'),
  'data-minimization': getBlogComponent('DataMinimizationBlog'),
  'data-privacy-obligations': getBlogComponent('DataPrivacyObligationsBlog'),
  'data-remanence': getBlogComponent('DataRemanenceBlog'),
  'data-remediation-erasure': getBlogComponent('DataRemediationErasureBlog'),
  'data-retention-privacy': getBlogComponent('DataRetentionPrivacyBlog'),
  'data-sanitization-compliance': getBlogComponent('DataSanitizationComplianceBlog'),
  'degaussing-risks': getBlogComponent('DegaussingRisksBlog'),
  'deleted-files-truth': getBlogComponent('DeletedFilesTruthBlog'),
  'deletion-vs-erasure': getBlogComponent('DeletionVsErasureBlog'),
  'dell-data-wipe-alternative': getBlogComponent('DellDataWipeAlternativeBlog'),
  'dell-data-wipe-vs-dsecure': getBlogComponent('DellDataWipeVsDSecureBlog'),
  'deployment-options': getBlogComponent('DeploymentOptionsBlog'),
  'diagnostics-erasure-itad': getBlogComponent('DiagnosticsErasureITADBlog'),
  'digital-divide': getBlogComponent('DigitalDivideBlog'),
  'dod-vs-ieee': getBlogComponent('DoDVsIEEEBlog'),
  'dod-vs-ieee-data-sanitization': getBlogComponent('DoDVsIEEEDataSanitizationBlog'),
  'dod-wiping-standard': getBlogComponent('DoDWipingStandardBlog'),
  'dsecure-operations': getBlogComponent('DSecureOperationsBlog'),
  'dumpster-diving-data-breach': getBlogComponent('DumpsterDivingDataBreachBlog'),
  'education-data-destruction': getBlogComponent('EducationDataDestructionBlog'),
  'end-of-life-data-security': getBlogComponent('EndOfLifeDataSecurityBlog'),
  'erase-data-pc-laptop-desktop': getBlogComponent('EraseDataPcLaptopDesktopBlog'),
  'erase-mac-data-safely-using-dsecure': getBlogComponent('EraseMacDataSafelyUsingDSecureBlog'),
  'erasure-as-a-service-dsecure': getBlogComponent('ErasureAsAServiceDSecureBlog'),
  'erasure-best-practices': getBlogComponent('ErasureBestPracticesBlog'),
  'erasure-verification-process': getBlogComponent('ErasureVerificationBlog'),
  'erasure-vs-destruction': getBlogComponent('ErasureVsDestructionBlog'),
  'esg-data-erasure': getBlogComponent('ESGDataErasureBlog'),
  'esg-report': getBlogComponent('ESGReportBlog'),
  'eu-csrd': getBlogComponent('EUCSRDBlog'),
  'financial-data-breach-case-study': getBlogComponent('FinancialDataBreachCaseStudyBlog'),
  'free-vs-pro-eraser': getBlogComponent('FreeVsProEraserBlog'),
  'future-data-destruction': getBlogComponent('FutureDataDestructionBlog'),
  'future-of-data-destruction-opportunities-challenges': getBlogComponent('FutureOfDataDestructionBlog'),
  'gdpr-seven-years': getBlogComponent('GDPRSevenYearsBlog'),
  'government-device-theft': getBlogComponent('GovernmentDeviceTheftBlog'),
  'government-device-theft-case-study': getBlogComponent('GovernmentDeviceTheftBlog'),
  'gov-device-theft': getBlogComponent('GovDeviceTheftBlog'),
  'government-it-disposal': getBlogComponent('GovernmentITDisposalBlog'),
  'green-it-practices': getBlogComponent('GreenITPracticesBlog'),
  'hardware-diagnostics': getBlogComponent('HardwareDiagnosticsBlog'),
  'hardware-diagnostics-itad-compliance': getBlogComponent('HardwareDiagnosticsITADComplianceBlog'),
  'healthcare-data-breach-case-study': getBlogComponent('HealthcareDataBreachCaseStudyBlog'),
  'healthcare-ransomware-lessons': getBlogComponent('HealthcareRansomwareLessonsBlog'),
  'hex-viewer': getBlogComponent('HexViewerBlog'),
  'hidden-disk-areas': getBlogComponent('HiddenDiskAreasBlog'),
  'hipaa-compliance-erasure': getBlogComponent('HIPAAComplianceErasureBlog'),
  'how-to-erase-mac': getBlogComponent('HowToEraseMacBlog'),
  'ieee-2883-2022-data-sanitization': getBlogComponent('IEEE2883ComplianceBlog'),
  'ipad-tablet-erasure': getBlogComponent('IPadTabletErasureBlog'),
  'it-asset-lifecycle': getBlogComponent('ITAssetLifecycleBlog'),
  'it-asset-reuse': getBlogComponent('ITAssetReuseBlog'),
  'itad-challenges': getBlogComponent('ITADChallengesBlog'),
  'itad-environmental': getBlogComponent('ITADEnvironmentalBlog'),
  'itad-market-growth': getBlogComponent('ITADMarketGrowthBlog'),
  'itad-procurement': getBlogComponent('ITADProcurementBlog'),
  'itad-selection-guide': getBlogComponent('ITADSelectionGuideBlog'),
  'itam-data-breach': getBlogComponent('ITAMDataBreachBlog'),
  'itam-disposal-guide': getBlogComponent('ITAMDisposalGuideBlog'),
  'legal-ethical-data-erasure': getBlogComponent('LegalEthicalDataErasureBlog'),
  'legal-ethical-erasure': getBlogComponent('LegalEthicalErasureBlog'),
  'loose-drives-erasure-guide': getBlogComponent('LooseDrivesErasureGuideBlog'),
  'm1-mac-erasure-issues': getBlogComponent('M1MacErasureIssuesBlog'),
  'mac-m1-erasure-known-issues': getBlogComponent('MacM1ErasureKnownIssues'),
  'marriott-settlement': getBlogComponent('MarriottSettlementBlog'),
  'mdm-detection': getBlogComponent('MDMDetectionBlog'),
  'media-sanitization-need': getBlogComponent('MediaSanitizationNeedBlog'),
  'mobile-diagnostics-benefits': getBlogComponent('MobileDiagnosticsBenefitsBlog'),
  'mobile-diagnostics-revolution': getBlogComponent('MobileDiagnosticsRevolutionBlog'),
  'mobile-erasure-guide': getBlogComponent('MobileErasureGuideBlog'),
  'morgan-stanley-data-breach': getBlogComponent('MorganStanleyDataBreachBlog'),
  'morgan-stanley-fine': getBlogComponent('MorganStanleyFineBlog'),
  'msp-data-erasure': getBlogComponent('MSPDataErasureBlog'),
  'msp-erasure-as-a-service': getBlogComponent('MSPErasureAsAServiceBlog'),
  'msp-erasure-service': getBlogComponent('MSPErasureServiceBlog'),
  'ncua-guidelines': getBlogComponent('NCUAGuidelinesBlog'),
  'ncua-third-party-data-disposal': getBlogComponent('NCUAThirdPartyDataDisposalBlog'),
  'nist-800-88-compliance-india': getBlogComponent('NIST80088IndiaBlog'),
  'nist-800-88-media-sanitization-guide': getBlogComponent('NIST80088MediaSanitizationBlog'),
  'nist-clear-purge': getBlogComponent('NISTClearPurgeBlog'),
  'nist-tested-erasure-software': getBlogComponent('NISTTestedErasureSoftwareBlog'),
  'nist-vs-ieee': getBlogComponent('NISTVsIEEEBlog'),
  'onsite-vs-offsite-destruction': getBlogComponent('OnsiteVsOffsiteDestructionBlog'),
  'overwrite-guide': getBlogComponent('OverwriteGuideBlog'),
  'phi-erasure': getBlogComponent('PHIErasureBlog'),
  'pii-disposal-breach': getBlogComponent('PIIDisposalBreachBlog'),
  'post-covid-data-disposal': getBlogComponent('PostCovidDataDisposalBlog'),
  'private-cloud': getBlogComponent('PrivateCloudBlog'),
  'remote-wiping-software': getBlogComponent('RemoteWipingSoftwareBlog'),
  'remote-work-data-erasure': getBlogComponent('RemoteWorkDataErasureBlog'),
  'remote-work-data-erasure-best-practices': getBlogComponent('RemoteWorkDataErasureBestPracticesBlog'),
  'reseller-profits': getBlogComponent('ResellerProfitsBlog'),
  'returning-leased-it-hardware-dos-and-donts': getBlogComponent('ReturningLeasedITHardwareDosAndDonts'),
  'right-to-repair': getBlogComponent('RightToRepairBlog'),
  'scope-3-emissions-reuse': getBlogComponent('Scope3EmissionsBlog'),
  'sec-compliance': getBlogComponent('SECComplianceBlog'),
  'secure-phi-ephi-erasure': getBlogComponent('SecurePHIePHIErasureBlog'),
  'secure-file-erase': getBlogComponent('SecureFileEraseBlog'),
  'secure-hdd-disposal': getBlogComponent('SecureHDDDisposalBlog'),
  'secure-it-asset-disposal': getBlogComponent('SecureITAssetDisposalBlog'),
  'secure-smartphone-erasure': getBlogComponent('SecureSmartphoneErasureBlog'),
  'server-erasure': getBlogComponent('ServerErasureBlog'),
  'shadow-data': getBlogComponent('ShadowDataBlog'),
  'shadow-data-risks': getBlogComponent('ShadowDataRisksBlog'),
  'ssd-wipe-bios': getBlogComponent('SSDWipeBIOSBlog'),
  'ssd-wipe-guide': getBlogComponent('SSDWipeGuideBlog'),
  'statutory-compliance': getBlogComponent('StatutoryComplianceBlog'),
  'statutory-regulatory-compliance-data-erasure': getBlogComponent('StatutoryRegulatoryComplianceDataErasureBlog'),
  'sustainable-it-reuse': getBlogComponent('SustainableITReuseBlog'),
  'ultratest-comparison': getBlogComponent('UltratestComparisonBlog'),
  'vm-erasure': getBlogComponent('VMErasureBlog'),
  'windows-10-eos': getBlogComponent('Windows10EOSBlog'),
  'wipe-computer-donating': getBlogComponent('WipeComputerDonatingBlog'),
  'wipe-ssd-from-bios-guide': getBlogComponent('WipeSSDFromBIOSGuide'),
  'world-class-nps': getBlogComponent('WorldClassNPSBlog'),
  'zero-trust-disposal': getBlogComponent('ZeroTrustDisposalBlog'),
  'physical-destruction-vs-data-wiping': getBlogComponent('PhysicalDestructionVsWipingBlog'),
  'msp-security-solutions': getBlogComponent('MSPSecurityBlog'),
  'brand-reputation-esg': getBlogComponent('BrandReputationESGBlog'),
  'chain-of-custody': getBlogComponent('ChainOfCustodyBlog'),
  'erasure-standards': getBlogComponent('ErasureBlog'),
};
